### ISSUE TITLE
How to assert no exception

### ISSUE THREAD

**Issue by spartanhooah** [stefanbirkner/system-lambda#11]
I'm trying to introduce `withEnvironmentVariable()` into the following (parameterized) test:
`assertDoesNotThrow(() -> testClass.testMethod(topicName));`
I tried to do the following, but `assertDoesNotThrow()` needs an executable. Is there any way to use your library in such a test?

**Comment by stefanbirkner** [comment]
Can you provide a complete example of a test that is not working? I tried

```java
assertDoesNotThrow(
    () -> withEnvironmentVariable("dummy name", "dummy value")
        .execute(() -> "return value")
);
```

and it works.

**Comment by spartanhooah** [comment]
Hmm, I can't remember what I'd tried now (I ended up using `junit-pioneer` instead), but I think I didn't realize what's inside `assertDoesNotThrow` needs to be a lambda (I haven't used JUnit 5 much).
