### ISSUE TITLE
Optional SystemExit Test

### ISSUE THREAD

**Issue by tomaculum** [stefanbirkner/system-lambda#21]
Hi,

is there a way to test for an optional `System.exit()`? 

If I implement

```java
String text = tapSystemOut(() -> {
    catchSystemExit(() -> Test.main());
});
assertEquals("abc", text);
```

and the main ends without an `System.exit()` call, I get the following Exception:

```
java.lang.AssertionError: System.exit has not been called.
```

If I do not include the `catchSystemExit()` part, it stops the execution of my test without a result.

Is there a way to achieve this kind of behaviour?

**Comment by ashleyfrieze** [comment]
@tomaculum  You may consider using https://github.com/webcompere/system-stubs#systemexit-class instead

This is an alternative library, which started as a fork of `system-stubs` and is more flexible.
