### ISSUE TITLE
SystemLambda class Documentation: examples assertThrownBy is an unknown method

### ISSUE THREAD

**Issue by MiBiT-Discuss** [stefanbirkner/system-lambda#25]
What happens 
Going through the example code in the documentation in the Readme and the SystemLambda class there are 5 references to the method `assertThrownBy`. The goal is to be able to use some examples using system-lambda.

Expected 
`assertThrownBy `to be sourced from somewhere.

Happens
it's unclear from what source this method is coming.

**Comment by stefanbirkner** [comment]
Thank you for your feedback. I used JUnit's assertions because I thought they are known by the audience. I think about how I can it make more clear. By the way, was it clear where `assertEquals` comes from?

**Comment by MiBiT-Discuss** [comment]
Stefan as far as I know "assertThrownBy" is from AssertJ and not Junit. I'm not familiar with an assertThrownBy in JUnit. I'd have to assume "assertEquals" is Junit. Correct?

**Comment by stefanbirkner** [comment]
You're right. `assertThrownBy` is AssertJ. JUnit uses `assertThrows`: https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions I fix the documentation.

**Comment by stefanbirkner** [comment]
Fixed in version 1.2.1: a5b7f466aeb32f2c237a08c3de6200ffdd9e850e
