### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by binkley** [stefanbirkner/system-lambda#26]
I may be missing something obvious, but I'm not finding a clear reference in `README.md` to where I can see release notes (ie, what changed between 1.2.1 and 1.2.0).

**Comment by stefanbirkner** [comment]
Only the Javadoc was fixed: a5b7f46. I add a changelog so that it is easier to see the changes.

**Comment by stefanbirkner** [comment]
There is now a changelog: Changelog.md.
