### ISSUE TITLE
Is there an example of how to use system-lambda in combination with Spring?

### ISSUE THREAD

**Issue by jimshowalter** [stefanbirkner/system-lambda#28]
We have a few remaining JUnit 4 tests that we're trying to migrate to JUnit 5.

We used system-lambda for others, but the remaining tests are Spring-based.

When we wrap the test code in system-lambda, it is unable to see @Autowired fields, so we get NPEs.

Is this simply not supported, or is there a way to make it work? If so, how?

**Comment by ashleyfrieze** [comment]
You should be able to access `@Autowired` fields from a unit test if you've got the `SpringExtension` on the test class to populate them. Can you provide an example of a test that's failing?

**Comment by jimshowalter** [comment]
I wound up refactoring the code to make it testable, so the examples are long gone.
