### ISSUE TITLE
Request: Return values for .execute(...)

### ISSUE THREAD

**Issue by NguyenAndrew** [stefanbirkner/system-lambda#6]
Hello! First off, I wanted to say thank you. I currently work for a Fortune 100 company, and we use this dependency to help unit test production Java AWS Lambdas that use environment variables (replacing previous system-rules and JUnit 4 dependency).

I noticed a possible improvement for this dependency, and I wanted to get your thoughts before working on the functionality and doing a pull request.

So if I had a unit test, and I want to simulate environment variables during a method call, I would have to use the API in the following manner.

```
@Test
myOldTest() {
    ...
    Example[] container = example[1];
    withEnvironmentVariable("first", "first value")
       .execute(() -> container[0] = objectUnderTest.methodUnderTest());
    Example actual = container[0];    

    assertEquals(expected, actual);
    ...
}
```

If we add the ability to not only use a void execute statement, but also have execute using a returning statement, we can have the following functionally.

```
@Test
myNewTest() {
    ...
    Example actual = withEnvironmentVariable("first", "first value")
       .apply(() -> objectUnderTest.methodUnderTest());    

    assertEquals(expected, actual);
    ...
}
```

I was thinking we can either reuse the execute method, or have the "returning execute" use a different method name.  Something else like `apply` (to avoid cases of ambiguity). Name chosen since it resembles Java 8's Functions https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html#apply-T-

Let me know, if there are any thoughts for adding this feature, and give me the go-ahead if you think it is worth implementing!

**Comment by stefanbirkner** [comment]
@NguyenAndrew Thanks for creating this feature request. I'm already close to finish the PR. I tell you when I'm ready so that you can have a look.

**Comment by stefanbirkner** [comment]
It is part of System Lambda 1.1.0: 7734d497fb37b364c63b95b923ceddf612f55efb
